# Generated by Django 3.2.7 on 2022-02-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('blog', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('category', models.CharField(blank=True, choices=[('SPRT', 'Спорт'), ('BIZNESS', 'Бизнес'), ('EDU', 'Образование')], max_length=15, null=True)),
            ],
            options={
                'ordering': ['title', 'blog', 'category'],
            },
        ),
        migrations.CreateModel(
            name='NewsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='news.news')),
            ],
        ),
    ]
